name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: ./frontend

      - name: build
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"
          VITE_ROOT_PATH: "/${{ github.event.repository.name }}"
          VITE_STORAGE_BASE_URL: ${{ vars.VITE_STORAGE_BASE_URL }}
        run: |
          pnpm run build
        working-directory: ./frontend

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "frontend/build/"

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
